import { News1, News2, News3, News4, News5, News6, News7, News8 } from './src/assets/img';
export const BlogList = [
  {
    id: 1,
    title: 'Jadwal Liga Inggris Pekan Ini Live di SCTV dan Vidio, 11-12 November 2023',
    image: 'https://cdns.klimg.com/bola.net/resized/810x540/library/upload/21/2023/08/996x664/premier-league-2023-_18636e5.jpg',
    totalComments: 89,
    totalLikes:2300,
    content: `Jadwal siaran langsung Premier League musim 2023/2024 di SCTV pekan ini, 11 hingga 12 November 2023. Siaran langsung Liga Inggris di SCTV pekan ini tidak ada dulu karena berbarengan dengan event Piala Dunia U-17 2023.`,
  },
  {
    id: 2,
    title: 'Prediksi Chelsea Vs Manchester City: The Citizens DijagokanBaca artikel sepakbola, "Prediksi Chelsea Vs Manchester City: The Citizens Dijagokan',
    image: 'https://cdn.vox-cdn.com/thumbor/o8B9jhgfU_pXkpIn4F6ypquucPA=/0x0:4305x2871/920x613/filters:focal(1739x901:2427x1589):format(webp)/cdn.vox-cdn.com/uploads/chorus_image/image/71839118/1454454774.0.jpg',
    totalComments: 89,
    totalLikes:2300,
    content: `Chelsea vs Manchester City akan tersaji di lanjutan Liga Inggris malam nanti. Prediksinya, The Citizens dijagokan jadi pemenang!`,
  },
  {
    id: 3,
    title: 'Indra Sjafri Harap Timnas U-17 Jangan Dibebani BerlebihanBaca artikel sepakbola, "Indra Sjafri Harap Timnas U-17 Jangan Dibebani Berlebihan"',
    image: 'https://akcdn.detik.net.id/visual/2023/05/13/indonesia-vs-vietnam-8_169.jpeg?w=650&q=90',
    totalComments: 89,
    totalLikes:2300,
    content: `Direktur Teknik PSSI Indra Sjafri berharap Timnas Indonesia U-17 tidak diberikan beban berlebihan.`,
  },
  {
    id: 4,
    title: 'Piala Dunia U-17',
    image: 'https://cdn.idntimes.com/content-images/community/2022/06/polish-20220605-122552431-1b6d1cd853484267ae86171b72dde9ea-d1173da033bd15c77b7bec6b05063e0b_600x400.jpg',
    totalComments: 89,
    totalLikes:2300,
    content: `Piala Dunia U-17: Wonderkid Barca Tak Sangka Dirinya Terkenal di IndonesiaBaca artikel sepakbola, "Piala Dunia U-17: Wonderkid Barca Tak Sangka Dirinya Terkenal di Indonesia", Marc Guiu mendapat sambutan positif dari pencinta sepakbola Indonesia di Solo. Dia bahkan tak sangka terkenal di Indonesia.`,
  },
  {
    id: 5,
    title: 'Heboh soal Rumput JIS, PSSI',
    image: 'https://akcdn.detik.net.id/community/media/visual/2023/07/04/rumput-di-jis-yang-bakal-diganti-dok-tim-erick-thohir_169.jpeg?w=700&q=90',
    totalComments: 89,
    totalLikes:2300,
    content: `Heboh soal Rumput JIS, PSSI: Lihat Langsung, Jangan dari TVBaca artikel sepakbola, "Heboh soal Rumput JIS, PSSI: Lihat Langsung, Jangan dari TV", Rumput Jakarta International Stadium dikritik netizen. Anggota Komite Eksekutif (Exco) PSSI, Arya Sinulingga, meminta pengkritik untuk lihat langsung, jangan dari televisi.`,
  },
  {
    id: 6,
    title: 'Hasil Voting Ballon d"Or 2023',
    image: 'https://cdns.klimg.com/bola.net/resized/810x540/library/upload/21/2023/10/996x664/messi-ballon-d-or_4e4ee30.jpg',
    totalComments: 89,
    totalLikes:2300,
    content: `Hasil Voting Ballon d'Or 2023: Messi Rupanya Jauh Ungguli HaalandBaca artikel sepakbola, "Hasil Voting Ballon d'Or 2023: Messi Rupanya Jauh Ungguli Haaland", Rupanya Lionel Messi menang Ballon d'Or 2023 dengan keunggulan yang cukup jauh dari Erling Halaand di posisi kedua. Berikut daftarnya.`,
  },
  {
    id: 7,
    title: 'Klasemen MotoGP 2023',
    image: 'https://akcdn.detik.net.id/visual/2023/09/23/motogp-india-2_169.jpeg?w=650&q=90',
    totalComments: 89,
    totalLikes:2300,
    content: `Klasemen MotoGP 2023: Bagnaia Jaga Jarak 14 Poin dari MartinBaca artikel detiksport, "Klasemen MotoGP 2023: Bagnaia Jaga Jarak 14 Poin dari Martin", Francesco Bagnaia terus puncaki Klasemen MotoGP 2023. Podium di MotoGP Malaysia 2023 membuat Pecco jaga jarak dari pesaing terdekatnya, Jorge Martin.`,
  },
  {
    id: 8,
    title: 'Harry Kane Menggila di Bundesliga',
    image: 'https://assets.goal.com/v3/assets/bltcc7a7ffd2fbf71f5/blt3416fdd56fde4fee/6548963eda791e040a18eb4e/GOAL_-_Blank_WEB_-_Facebook_-_2023-11-06T073033.747.png?auto=webp&format=pjpg&width=640&quality=60',
    totalComments: 89,
    totalLikes:2300,
    content: `Harry Kane Menggila di Bundesliga, Top Skor Musim Lalu Lewat!Baca artikel sepakbola, "Harry Kane Menggila di Bundesliga, Top Skor Musim Lalu Lewat!", Aliran gol Harry Kane di Bundesliga bersama Bayern Munich terus mengucur deras. Jumlah golnya bahkan sudah melewati total gol top skor musim lalu!`,
  },
];